version: "3.7"
services:
  relay:
    restart: "unless-stopped"
    ports:
      - 7546:7546
    pull_policy: always
    tty: true
    volumes:
      - ./.env:/home/node/app/.env
  relay-ws:
    command: 
      - npm
      - run
      - start:ws
    environment:
      HEALTHCHECK_PORT: 8547
      SUBSCRIPTIONS_ENABLED: "true"
    restart: "unless-stopped"
    ports:
      - 8546:8546
      - 8547:8547
    pull_policy: always
    tty: true
    volumes:
      - ./.env:/home/node/app/.env
